name: Request Unity Activation File

on:
  workflow_dispatch:

jobs:
  request-alf:
    name: Request .alf (${{ matrix.unity-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        unity-version:
          - 2020.3.48f1
          - 2021.3.39f1
          - 2022.3.70f1
          - 6000.0.47f1

    steps:
      - name: Request activation file
        uses: game-ci/unity-request-activation-file@v2
        id: getAlf
        with:
          unityVersion: ${{ matrix.unity-version }}

      - name: Upload .alf
        uses: actions/upload-artifact@v4
        with:
          name: alf-${{ matrix.unity-version }}
          path: ${{ steps.getAlf.outputs.filePath }}
