name: Test

on:
  pull_request:
    branches: [main, dev]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: dotnet test
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore Packages/com.mu5dvlp.qulacs/dotnet~/Mu5dvlp.Qulacs.Tests.csproj

      - name: Build
        run: dotnet build Packages/com.mu5dvlp.qulacs/dotnet~/Mu5dvlp.Qulacs.Tests.csproj --no-restore

      - name: Test
        run: >-
          dotnet test Packages/com.mu5dvlp.qulacs/dotnet~/Mu5dvlp.Qulacs.Tests.csproj
          --no-build
          --logger "trx;LogFileName=test-results.trx"
          --results-directory test-results

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results
